export const QuotesListHeader = [
  { field: "Quotation_No", header: "Quotation No" },
  { field: "From_date", header: "From date" },
  { field: "To_Date", header: "To Date" },
  { field: "Status", header: "Status" },
  { field: "action", header: "" },
];
export const QuotesList = {
  data: [
    {
      key: 361,
      LOB_Code: "10",
      Quot_list: [
        {
          key: 76402,
          Quotation_No: "Q/001/01/10/T1002/2012/000002",
          From_date: "03/10/2012 14:21:02",
          To_Date: "02/10/2013 23:59:00",
          Status: "Incomplete",
        },
        {
          key: 138693,
          Quotation_No: "Q/001/01/10/T1002/2014/000003",
          From_date: "28/11/2014 00:00:00",
          To_Date: "27/11/2015 23:59:00",
          Status: "Incomplete",
        },
        {
          key: 138860,
          Quotation_No: "Q/001/01/10/T1002/2014/000005",
          From_date: "04/12/2014 12:23:19",
          To_Date: "03/12/2015 23:59:00",
          Status: "Incomplete",
        },
        {
          key: 273069,
          Quotation_No: "Q/001/01/10/U1002/2016/000007",
          From_date: "22/09/2016 11:38:50",
          To_Date: "21/09/2017 23:59:00",
          Status: "Incomplete",
        },
        {
          key: 287626,
          Quotation_No: "Q/001/01/10/T1002/2017/000008",
          From_date: "18/07/2017 09:47:31",
          To_Date: "17/09/2017 23:59:00",
          Status: "Approved",
        },
        {
          key: 217292,
          Quotation_No: "Q/001/01/10/T1002/2015/000006",
          From_date: "15/09/2015 14:48:49",
          To_Date: "14/09/2016 23:59:00",
          Status: "Rejected",
        },
      ],
    },
    {
      key: 361,
      LOB_Code: "11",
      Quot_list: [
        {
          key: 76402,
          Quotation_No: "Q/001/01/10/T1002/2012/000002",
          From_date: "03/10/2012 14:21:02",
          To_Date: "02/10/2013 23:59:00",
          Status: "Incomplete",
        },
        {
          key: 138693,
          Quotation_No: "Q/001/01/10/T1002/2014/000003",
          From_date: "28/11/2014 00:00:00",
          To_Date: "27/11/2015 23:59:00",
          Status: "Incomplete",
        },
        {
          key: 138860,
          Quotation_No: "Q/001/01/10/T1002/2014/000005",
          From_date: "04/12/2014 12:23:19",
          To_Date: "03/12/2015 23:59:00",
          Status: "Incomplete",
        },
        {
          key: 273069,
          Quotation_No: "Q/001/01/10/U1002/2016/000007",
          From_date: "22/09/2016 11:38:50",
          To_Date: "21/09/2017 23:59:00",
          Status: "Incomplete",
        },
        {
          key: 287626,
          Quotation_No: "Q/001/01/10/T1002/2017/000008",
          From_date: "18/07/2017 09:47:31",
          To_Date: "17/09/2017 23:59:00",
          Status: "Approved",
        },
        {
          key: 217292,
          Quotation_No: "Q/001/01/10/T1002/2015/000006",
          From_date: "15/09/2015 14:48:49",
          To_Date: "14/09/2016 23:59:00",
          Status: "Rejected",
        },
      ],
    },
  ],
};

export const headerData = {
  data: [
    {
      key: 76402,
      LOB: "10-Motor",
      Product: "1002-Motor Commercial",
      branch: "01-Head Office",
      department: "10-Motor",
      businessType: "1-Direct without coinsurance",
      quotaion: "Q/001/01/10/T1002/2012/000002",
      recordDate: "03/10/2012 00:00:00",
      period: 7,
      sourceType: "1-Direct",
      "Source Code": null,
      unit: "2-Day",
      issueDate: "03/10/2012 00:00:00",
      periodFrom: "03/10/2012 14:21:02",
      periodTo: "02/10/2013 23:59:00",
      premiumType: "3-Normal/Annual",
      currency: "005-TANZANIAN SHILLINGS",
      premiumCurrency: "005-TANZANIAN SHILLINGS",
      paymentMode: "CC-Credit Customer",
      installment: null,
      preInspection: "0",
      territory: "Kuwait",
      oldPolicy: null,
      fleet: "0",
      gracePeriod: null,
      gracePeriodEnd: null,
      cbc: null,
      coverNoteId: null,
      coverNote: null,
      coverNoteDate: null,
      plan: "Gold",
      address: "ADDRESS1",
      Area: null,
      State: null,
      City: null,
      partyDetails: [
        {partyRole: "Customer", partyID: "DC0001001", address: "" },
        {partyRole: "Insured", partyID: "BL1011470", address: "ADDRESS2" },
      ],
    },
  ],
};

export const data = [
  {
    key: 2301,
    Objects: [
      {
        Id: "R_01",
        Object_name: "Vehicle Details",
        Fields: [
          {
            Field_Id: 1,
            Field_Name: "Vehicle ID",
            Serial_no: 1,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "0",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 2,
            Field_Name: "Vehicle Entry Date",
            Serial_no: 2,
            Data_Type: "Date",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "0",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 3,
            Field_Name: "Vehicle Exit Date",
            Serial_no: 3,
            Data_Type: "Date",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "0",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 4,
            Field_Name: "Usage Type",
            Serial_no: 4,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 5,
            Field_Name: "Coverage Type",
            Serial_no: 5,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 6,
            Field_Name: "Body Type",
            Serial_no: 6,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 7,
            Field_Name: "Make*",
            Serial_no: 7,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 8,
            Field_Name: "Model",
            Serial_no: 8,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 9,
            Field_Name: "Mfg Year",
            Serial_no: 9,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 10,
            Field_Name: "Vehicle Age",
            Serial_no: 10,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "0",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 11,
            Field_Name: "Engine No.",
            Serial_no: 11,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 12,
            Field_Name: "Chassis No.",
            Serial_no: 12,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 13,
            Field_Name: "Registration No.",
            Serial_no: 13,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 14,
            Field_Name: "CC",
            Serial_no: 14,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 15,
            Field_Name: "Fuel Type",
            Serial_no: 15,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 16,
            Field_Name: "Vehicle Value",
            Serial_no: 16,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 17,
            Field_Name: "Seating",
            Serial_no: 17,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 18,
            Field_Name: "GVW",
            Serial_no: 18,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 19,
            Field_Name: "No.of Claims",
            Serial_no: 19,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 20,
            Field_Name: "No. of Claim free years",
            Serial_no: 20,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 21,
            Field_Name: "Sum Insured Currency",
            Serial_no: 21,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 22,
            Field_Name: "Premium Currency",
            Serial_no: 22,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
        ],
      },
    ],
  },
];
