export const getQuotesInitialData = [
  {
    quotation: "",
    product: "",
    start_date: "",
    end_date: "",
    status: "",
  },
];

export const getquotesOption = [
  {
    type: "motor",
    name: "1001-Motor Comprehension",
    code: 10,
  },
  {
    type: "motor",
    name: "1002-Motor Private",
    code: 20,
  },
  {
    type: "marine",
    name: "1003-Marine Open Cover",
    code: 30,
  },
  {
    type: "fire",
    name: "1004-Fire Open Cover",
    code: 40,
  },
];

export const getQuotesTableData = [
  {
    id: 1,
    quotation: "Q/10/1001/2024/0543",
    product: "Motor Comprehension",
    start_date: "10/01/2024",
    end_date: "10/01/2024",
    status: "Pending",
  },
  {
    id: 2,
    quotation: "Q/10/1001/2024/0544",
    product: "Motor Private",
    start_date: "10/01/2024",
    end_date: "10/01/2024",
    status: "Pending",
  },
];

export const headerFormOptionData = {
  product: [
    { name: "1-Product", code: 1 },
    { name: "2-Product", code: 2 },
  ],
  branch: [
    { Code: "03", name: "Mbeya Branch" },
    { Code: "01", name: "Head Office" },
    { Code: "02", name: "Mwanza Branch" },
    { Code: "04", name: "Arusha Branch" },
    { Code: "06", name: "Mbagala Branch" },
    { Code: "05", name: "Dodoma Branch" },
    { Code: "07", name: "Digital-sure Branch" },
    { Code: "08", name: "Zanzibar Branch" },
  ],
  businessType: [
    { code: "01", name: "Direct without coisurance" },
    { code: "02", name: "Direct with Coinsurance" },
  ],
  sourceType: [
    { code: "01", name: "Direct" },
    { code: "02", name: "Agent" },
    { code: "03", name: "Broker" },
  ],
  unit: [
    { code: "1", name: "Hour" },
    { code: "2", name: "Day" },
    { code: "3", name: "Week" },
    { code: "4", name: "Month" },
    { code: "5", name: "Year" },
  ],
  premiumType: ["Pro-Rate", "Short Period", "Normal/Annual", "Fixed Rate"],
  paymentMode: ["Bank Guarantee", "Credit Customer", "Others"],
  installment: ["Annual", "Half-Yearly", "Quarterly", "Monthly"],
  state: ["Tamil Nadu", "Karnataka", "Andra"],
  city: ["chennai", "Coimbatore"],
  area: ["Tiruvanmiyur", "Adayar", "Perungudi"],
};

export const searchDisplayData = {
  data: [
    {
      id: "DC0001001",
      name: "Shankar",
      email: "shankar@gmail.com",
      phoneno: 9876543210,
    },
    {
      id: "BL1011470",
      name: "Hari",
      email: "sari@gmail.com",
      phoneno: 1234567890,
    },
    {
      id: "SA1011580",
      name: "Siva",
      email: "hiva@gmail.com",
      phoneno: 9090909090,
    },
  ],
};

export const searchDisplayHeader = [
  { field: "name", header: "Name" },
  { field: "email", header: "Email" },
  { field: "phoneno", header: "Phoneno" },
];

export const getQuotesHeaderFromRender = {
  partyDetails: [
    {
      name: "partyRole",
      label: "Party Role",
      fieldType: "dropDown",
      required: true,
    },
    {
      name: "partyID",
      label: "Party ID",
      fieldType: "overlay",
      required: true,
    },
    {
      name: "address",
      label: "Address",
      fieldType: "partyAddress",
    },
  ],
  formData: [
    { name: "plan", label: "plan", fieldType: "autoComplete", required: true },
    { name: "branch", label: "Branch", fieldType: "dropDown", required: true },
    {
      name: "department",
      label: "department",
      fieldType: "inputText",
      required: true,
    },
    {
      name: "businessType",
      label: "business type",
      fieldType: "dropDown",
      required: true,
    },
    {
      name: "quotaion",
      label: "quotaion#",
      fieldType: "inputText",
      disabled: true,
      readonly: true,
    },
    { name: "recordDate", label: "quote record Date", fieldType: "dateType" },
    // {
    //   name: "customer",
    //   label: "customer",
    //   fieldType: "overlay",
    //   required: true,
    // },
    // { name: "insured", label: "insured", fieldType: "overlay", required: true },
    // { name: "sourceCode", label: "source Code", fieldType: "autoComplete" },
    { name: "sourceType", label: "source type", fieldType: "dropDown" },
    { name: "unit", label: "unit", fieldType: "dropDown" },
    { name: "period", label: "period", fieldType: "inputNumber" },
    { name: "issueDate", label: "issue date", fieldType: "dateType" },
    {
      name: "periodFrom",
      label: "period form",
      fieldType: "dateType",
      required: true,
    },
    {
      name: "periodTo",
      label: "period to",
      fieldType: "dateType",
      required: true,
    },
    {
      name: "premiumType",
      label: "premium calculate type",
      fieldType: "dropDown",
      required: true,
    },
    { name: "currency", label: "SI currency", fieldType: "autoComplete" },
    {
      name: "premiumCurrency",
      label: "premium currency",
      fieldType: "autoComplete",
    },
    { name: "paymentMode", label: "mode of payment", fieldType: "inputText" },
    { name: "installment", label: "installment Method", fieldType: "dropDown" },
    {
      name: "hypothecation",
      label: "hypothecation Yes / No",
      fieldType: "checkBox",
    },
    {
      name: "preInspection",
      label: "pre-inspection yes / no",
      fieldType: "checkBox",
    },
    { name: "territory", label: "territory", fieldType: "inputText" },
    { name: "oldPolicy", label: "old Policy #", fieldType: "inputText" },
    { name: "fleet", label: "fleet yes / no", fieldType: "checkBox" },
    {
      name: "gracePeriod",
      label: "grace period yes / no",
      fieldType: "checkBox",
    },
    {
      name: "gracePeriodEnd",
      label: "grace period end date",
      fieldType: "dateType",
    },
    { name: "cbc", label: "CBC yes / No", fieldType: "checkBox" },
    {
      name: "coverNoteId",
      label: "cover note book id",
      fieldType: "autoComplete",
    },
    { name: "coverNote", label: "cover note", fieldType: "inputText" },
    { name: "coverNoteDate", label: "cover note date", fieldType: "dateType" },
    { name: "state", label: "State", fieldType: "dropDown" },
    { name: "city", label: "City", fieldType: "dropDown" },
    { name: "area", label: "Area", fieldType: "dropDown" },
    {
      name: "address",
      label: "Address",
      fieldType: "address",
    },
  ],
};

export const getQuotesHeaderData = {
  partyDetails: [
    { partyRole: "Customer", partyID: "", address: "" },
    { partyRole: "Insured", partyID: "", address: "" },
  ],
  formData: {
    branch: "01-Head Office",
    department: "11-Motor UW department",
    businessType: "1-Direct with Coinsurance",
    quotaion: "",
    recordDate: "07/06/2024 08:31",
    // customer: "",
    // insured: "",
    // sourceCode: "",
    sourceType: "",
    unit: "Day",
    period: "365",
    issueDate: "",
    periodFrom: "",
    periodTo: "",
    premiumType: "Normal/Annual",
    currency: "",
    premiumCurrency: "",
    paymentMode: "Credit Customer",
    installment: "Quarterly",
    hypothecation: "",
    preInspection: "",
    territory: "",
    oldPolicy: "",
    fleet: "",
    gracePeriod: "",
    gracePeriodEnd: "",
    cbc: "",
    coverNoteId: "",
    coverNote: "",
    coverNoteDate: "",
    address: "",
    plan: "",
  },
};

export const getQuotesTabData = {
  discountLoading: {
    value: [
      { name: "Own Damage", code: "3101", mandatory: true },
      { name: "Third party Death ", code: "3176", mandatory: true },
      { name: "Third party property damage", code: "3178", mandatory: true },
      { name: "PA Benefit to Driver", code: "3106", mandatory: false },
      { name: "Road Assistance", code: "3195", mandatory: false },
      { name: "Agency Repair", code: "3103", mandatory: false },
      { name: "Natural Calamity Cover", code: "3104", mandatory: false },
      { name: "Geographical Extension", code: "3105", mandatory: false },
      { name: "Personal Accident Passenger", code: "3102", mandatory: false },
    ],
  },
};

export const getQuotesTableHeaderData = {
  discountLoading: {
    header: [
      { field: "code", header: "Code", fieldType: "dropDown" },
      {
        field: "description",
        header: "Description",
        fieldType: "inputTextarea",
      },
      { field: "rate", header: "Rate", fieldType: "inputNumber" },
      { field: "rateper", header: "Rate Per", fieldType: "inputNumber" },
      { field: "amounttc", header: "Amount TC", fieldType: "inputNumber" },
      { field: "amountlc", header: "Amount LC", fieldType: "inputNumber" },
      {
        field: "canscadeOrder",
        header: "Cascade Order",
        fieldType: "inputNumber",
      },
      { field: "applied", header: "Applied On", fieldType: "dropDown" },
      {
        field: "brokercomm",
        header: "Broker Comm. Appl",
        fieldType: "checkBox",
      },
      { field: "ncb", header: "NCB Yes / NO", fieldType: "checkBox" },
      { field: "save", header: "" },
      { field: "action", header: "" },
    ],
  },
  deductible: {
    header: [
      { field: "code", header: "Code", fieldType: "inputText" },
      {
        field: "description",
        header: "Description",
        fieldType: "inputTextarea",
      },
      {
        field: "deductibleType",
        header: "Deductible Type",
        fieldType: "inputNumber",
      },
      { field: "percentage", header: "%", fieldType: "inputNumber" },
      { field: "amounttc", header: "Amount TC", fieldType: "inputNumber" },
      { field: "amountlc", header: "Amount LC", fieldType: "inputNumber" },
      { field: "save", header: "" },
      { field: "action", header: "" },
    ],
  },
  conditions: {
    header: [
      { field: "code", header: "Code", fieldType: "dropDown" },
      {
        field: "description",
        header: "Description",
        fieldType: "inputTextarea",
      },
      {
        field: "longDescription",
        header: "Long Description",
        fieldType: "inputTextarea",
      },
      {
        field: "longDescription2",
        header: "Long Description",
        fieldType: "inputTextarea",
      },
      {
        field: "conditionType",
        header: "Condition Type",
        fieldType: "inputNumber",
      },
      { field: "save", header: "" },
      { field: "action", header: "" },
    ],
  },
  chargeTax: {
    header: [
      { field: "type", header: "Type", fieldType: "autoComplete" },
      { field: "charge", header: "Charge", fieldType: "autoComplete" },
      { field: "level", header: "Level", fieldType: "inputNumber" },
      { field: "rate", header: "Rate", fieldType: "inputNumber" },
      { field: "rateper", header: "Rate Per", fieldType: "inputNumber" },
      {
        field: "customerPercentage",
        header: "Customer %",
        fieldType: "inputNumber",
      },
      { field: "chargetc", header: "Charge TC", fieldType: "inputNumber" },
      { field: "chargelc", header: "Charge LC", fieldType: "inputNumber" },
      { field: "save", header: "" },
      { field: "action", header: "" },
    ],
  },
  commission: {
    header: [
      { field: "agent", header: "Agent", fieldType: "dropDown" },
      { field: "commission", header: "Commission", fieldType: "dropDown" },
      { field: "appliedOn", header: "Applied On", fieldType: "dropDown" },
      { field: "currency", header: "Currency", fieldType: "inputNumber" },
      {
        field: "commissiontc",
        header: "Commission TC",
        fieldType: "inputNumber",
      },
      {
        field: "commissionlc",
        header: "Commission LC",
        fieldType: "inputNumber",
      },
      { field: "save", header: "" },
      { field: "action", header: "" },
    ],
  },
  applicableCurrency: {
    header: [
      { field: "currency", header: "Currency", fieldType: "autoComplete" },
      { field: "rateType", header: "Rate Type", fieldType: "dropDown" },
      { field: "rate1", header: "US Dollar", fieldType: "inputNumber" },
      { field: "rate2", header: "Indian Rupees", fieldType: "inputNumber" },
      { field: "rate3", header: "japaneseYen", fieldType: "inputNumber" },
      { field: "save", header: "" },
      { field: "action", header: "" },
    ],
  },
  hypothecation: {
    header: [
      { field: "sri", header: "Serial No.", fieldType: "inputText" },
      { field: "financier", header: "Financier", fieldType: "dropDown" },
      { field: "hypoType", header: "Hypo. Type", fieldType: "dropDown" },
      { field: "ref", header: "Reference", fieldType: "inputText" },
      { field: "webite", header: "Webite", fieldType: "inputText" },
      { field: "phone", header: "Phone", fieldType: "inputNumber" },
      { field: "save", header: "" },
      { field: "action", header: "" },
    ],
  },
  prevInsurenceDetails: {
    header: [
      { field: "insurer", header: "Insurer", fieldType: "inputText" },
      { field: "fromDate", header: "From Date", fieldType: "dateField" },
      { field: "uwYear", header: "UW Year", fieldType: "inputText" },
      { field: "plicy", header: "Policy", fieldType: "inputText" },
      { field: "sumInsured", header: "Sum Insured", fieldType: "inputText" },
      { field: "premium", header: "Premium", fieldType: "inputText" },
      { field: "claim", header: "Claim", fieldType: "inputText" },
      { field: "claimRatio", header: "Claim Ratio", fieldType: "inputNumber" },
      { field: "save", header: "" },
      { field: "action", header: "" },
    ],
  },
  surveyorDetails: {
    header: [
      { field: "surveyor", header: "Surveyor", fieldType: "dropDown" },
      { field: "feesType", header: "Fees Type", fieldType: "dropDown" },
      {
        field: "calculationType",
        header: "Calculation Type",
        fieldType: "dropDown",
      },
      { field: "currency", header: "Currency", fieldType: "dropDown" },
      { field: "feesTc", header: "Fees TC", fieldType: "inputText" },
      { field: "feesLc", header: "Fees LC", fieldType: "inputText" },
      { field: "save", header: "" },
      { field: "action", header: "" },
    ],
  },
  riDetails: {
    header: [
      { field: "riBasic", header: "RI Basic", fieldType: "dropDown" },
      { field: "cedingBasis", header: "Ceding Basis", fieldType: "dropDown" },
      { field: "riPremType", header: "RI Prem Type", fieldType: "dropDown" },
      {
        field: "deductRi",
        header: "Deduct RI Communication",
        fieldType: "dropDown",
      },
      {
        field: "endAllocation",
        header: "End Allocation",
        fieldType: "dropDown",
      },
      { field: "facProvOn", header: "FAC Prov. On", fieldType: "dropDown" },
      { field: "save", header: "", fieldType: "" },
    ],
  },
};

export const quotesTabTableInitialData = {
  discountLoading: {
    value: [
      {
        code: "",
        description: "",
        rate: "",
        ratePer: "",
        amountTC: "",
        amountLC: "",
        order: "",
        commAppl: "",
        nub: "",
      },
    ],
  },
  deductible: {
    value: [
      {
        code: "",
        description: "",
        deductibleType: "",
        percentage: "",
        amounttc: "",
        amountlc: "",
      },
    ],
  },
  conditions: {
    value: [
      {
        code: "",
        description: "",
        longDescription: "",
        longDescription2: "",
        conditionType: "",
      },
    ],
  },
  chargeTax: {
    value: [
      {
        type: "",
        charge: "",
        level: "",
        rate: "",
        rateper: "",
        customerPercentage: "",
        chargetc: "",
        chargelc: "",
      },
    ],
  },
  commission: {
    value: [
      {
        agent: "",
        commission: "",
        appliedOn: "",
        currency: "",
        commissiontc: "",
        commissionlc: "",
      },
    ],
  },
  applicableCurrency: {
    value: [
      {
        currency: "",
        rateType: "",
        rate1: "",
        rate2: "",
        rate3: "",
        save: "",
      },
    ],
  },
  hypothecation: {
    value: [
      {
        sri: "",
        financier: "",
        hypoType: "",
        ref: "",
        webite: "",
        phone: "",
        save: "",
      },
    ],
  },
  prevInsurenceDetails: {
    value: [
      {
        insurer: "",
        fromDate: "",
        uwYear: "",
        plicy: "",
        sumInsured: "",
        premium: "",
        claim: "",
        claimRatio: "",
        save: "",
      },
    ],
  },
  surveyorDetails: {
    value: [
      {
        surveyor: "",
        feesType: "",
        calculationType: "",
        currency: "",
        feesTc: "",
        feesLc: "",
        save: "",
      },
    ],
  },
  riDetails: {
    value: [
      {
        riBasic: "",
        cedingBasis: "",
        riPremType: "",
        deductRi: "",
        endAllocation: "",
        facProvOn: "",
      },
    ],
  },
};

export const quotesTabFillTableData = {
  data: [
    {
      key: 76402,
      conditions: [
        {
          code: "3",
          description: "04   Authorised Repair Limit [Section 1 - 4 (a)]",
          longDescription:
            ".................................................... 750,000.00 TSHS",
          conditionType: "06",
        },
        {
          code: "1",
          description: "01   Section 1 - 3",
          longDescription:
            "(Protection and Removal)/Towing Charges 250,000 TSHS.",
          conditionType: "06",
        },
        {
          code: "7",
          description: "02   Section II-1(a) and 2(a)",
          longDescription:
            "(Liability to Third Parties death or bodily injury) in respect of any one claim or series of claims arising out of one event - Unlimited.",
          conditionType: "06",
        },
        {
          code: "9",
          description: "03   Section II-1(b) and 2(b)",
          longDescription:
            "(Liability to Third Parties - Property Damage) in respect of any one claim or series of claims arising out of one event 30,000,000.00 TSHS.",
          conditionType: "06",
        },
      ],
      applicableCurrency: [
        {
          code: "005",
          rateType: "UGANDA  SHILLINGS",
          rate1: 1,
          rate2: 1,
          rate3: 1,
        },
      ],
    },
  ],
};

export const riskBlock = [
  {
    key: 2301,
    Id: "R_01",
    displayName: "motor",
    name: "vehicleDetails",
    Object_name: "Vehicle Details",
    Parent_Object_Id: null,
    Level: 1,
    Serial_no: 1,
    Object_Type: "2",
    Submenu: [
      {
        Id: "R_16",
        name: "geographicDetail",
        Object_name: "Geographical Extension",
        Parent_Object_Id: "R_01",
        Level: 2,
        Serial_no: 1,
        Object_Type: "2",
      },
    ],
  },
  {
    key: 2301,
    Id: "R_02",
    displayName: "motor",
    name: "driverDetails",
    Object_name: "Driver Details",
    Parent_Object_Id: null,
    Level: 1,
    Serial_no: 2,
    Object_Type: "2",
    submenu: [],
  },
  {
    key: 76402,
    Id: "R_102",
    displayName: "fire",
    name: "locationDetails",
    Object_name: "Location Details",
    Parent_Object_Id: null,
    Level: 1,
    Serial_no: 1,
    Object_Type: "2",
    Submenu: [
      {
        Id: "R_116",
        name: "contentDetails",
        Object_name: "Content Extension",
        Parent_Object_Id: "R_102",
        Level: 2,
        Serial_no: 1,
        Object_Type: "2",
      },
    ],
  },
];

export const riskFactor = {
  vehicleDetails: {
    key: 2301,
    Objects: [
      {
        Id: "R_01",
        Object_name: "Vehicle Details",
        Fields: [
          {
            Field_Id: 1,
            Field_Name: "Vehicle ID",
            Serial_no: 1,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "0",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 2,
            Field_Name: "Vehicle Entry Date",
            Serial_no: 2,
            Data_Type: "Date",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "0",
            Field_type: "Date",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 3,
            Field_Name: "Vehicle Exit Date",
            Serial_no: 3,
            Data_Type: "Date",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "0",
            Field_type: "Date",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 4,
            Field_Name: "Usage Type",
            Serial_no: 4,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 5,
            Field_Name: "Coverage Type",
            Serial_no: 5,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 6,
            Field_Name: "Body Type",
            Serial_no: 6,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 7,
            Field_Name: "Make*",
            Serial_no: 7,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 8,
            Field_Name: "Model",
            Serial_no: 8,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 9,
            Field_Name: "Mfg Year",
            Serial_no: 9,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 10,
            Field_Name: "Vehicle Age",
            Serial_no: 10,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "0",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 11,
            Field_Name: "Engine No.",
            Serial_no: 11,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 12,
            Field_Name: "Chassis No.",
            Serial_no: 12,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 13,
            Field_Name: "Registration No.",
            Serial_no: 13,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 14,
            Field_Name: "CC",
            Serial_no: 14,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 15,
            Field_Name: "Fuel Type",
            Serial_no: 15,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 16,
            Field_Name: "Vehicle Value",
            Serial_no: 16,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 17,
            Field_Name: "Seating",
            Serial_no: 17,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 18,
            Field_Name: "GVW",
            Serial_no: 18,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 19,
            Field_Name: "No.of Claims",
            Serial_no: 19,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 20,
            Field_Name: "No. of Claim free years",
            Serial_no: 20,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 21,
            Field_Name: "Sum Insured Currency",
            Serial_no: 21,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 22,
            Field_Name: "Premium Currency",
            Serial_no: 22,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
        ],
      },
    ],
  },
  driverDetails: {
    key: 2301,
    Objects: [
      {
        Id: "R_02",
        Object_name: "Driver Details",
        Fields: [
          {
            Field_Id: 1,
            Field_Name: "Driver Name",
            Serial_no: 1,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 2,
            Field_Name: "Date of Birth",
            Serial_no: 2,
            Data_Type: "Date",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "Date",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 3,
            Field_Name: "Age*",
            Serial_no: 3,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "0",
            Field_type: null,
            List_values_source: "inputNumber",
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 4,
            Field_Name: "Gender*",
            Serial_no: 4,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 5,
            Field_Name: "Marital Status",
            Serial_no: 5,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 6,
            Field_Name: "Nationality*",
            Serial_no: 6,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 7,
            Field_Name: "Driver Id/Licence No.*",
            Serial_no: 7,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 8,
            Field_Name: "Type of Licence",
            Serial_no: 8,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 9,
            Field_Name: "Licence Issue Date",
            Serial_no: 9,
            Data_Type: "Date",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "Date",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 10,
            Field_Name: "Licence Expiry Date",
            Serial_no: 10,
            Data_Type: "Date",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "Date",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 11,
            Field_Name: "Licence Age",
            Serial_no: 11,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 12,
            Field_Name: "Issue At",
            Serial_no: 12,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
        ],
      },
    ],
  },
  geographicDetail: {
    key: 2301,
    Objects: [
      {
        Id: "R_16",
        Object_name: "Geographical Extension",
        Fields: [
          {
            Field_Id: 1,
            Field_Name: "Sr No.",
            Serial_no: 1,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputText",
            List_values_source: null,
          },
          {
            Field_Id: 2,
            Field_Name: "Place of Travel",
            Serial_no: 2,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputText",
            List_values_source: null,
          },
          {
            Field_Id: 10,
            Field_Name: "ExtensionPeriod Units",
            Serial_no: 3,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
          },
          {
            Field_Id: 3,
            Field_Name: "Period",
            Serial_no: 4,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
          },
          {
            Field_Id: 4,
            Field_Name: "Effective From",
            Serial_no: 5,
            Data_Type: "Date",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "Date",
            List_values_source: null,
          },
          {
            Field_Id: 5,
            Field_Name: "Effective To",
            Serial_no: 6,
            Data_Type: "Date",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "Date",
            List_values_source: null,
          },
          {
            Field_Id: 6,
            Field_Name: "Premium Tc",
            Serial_no: 7,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
          },
          {
            Field_Id: 7,
            Field_Name: "Premium LC",
            Serial_no: 8,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
          },
          {
            Field_Id: 8,
            Field_Name: "Remarks",
            Serial_no: 9,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputTextarea",
            List_values_source: null,
          },
          {
            Field_Id: 9,
            Field_Name: "No. of Claims",
            Serial_no: 10,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
          },
        ],
      },
    ],
  },
  locationDetails: {
    key: 76402,
    Objects: [
      {
        Id: "R_102",
        Object_name: "Location Details",
        Fields: [
          {
            Field_Id: 1,
            Field_Name: "Risk ID",
            Serial_no: 1,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "0",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 2,
            Field_Name: "Risk Effective From Date",
            Serial_no: 2,
            Data_Type: "Date",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "0",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 3,
            Field_Name: "Risk Effective To Date",
            Serial_no: 3,
            Data_Type: "Date",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "0",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 4,
            Field_Name: "Type of Occupancy",
            Serial_no: 4,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 5,
            Field_Name: "Risk Category",
            Serial_no: 5,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 6,
            Field_Name: "Risk sub Category",
            Serial_no: 6,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 7,
            Field_Name: "Risk Class",
            Serial_no: 7,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "dropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 8,
            Field_Name: "Building AGe",
            Serial_no: 9,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 9,
            Field_Name: "Vehicle Age",
            Serial_no: 10,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "0",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 10,
            Field_Name: "Google Integration Required",
            Serial_no: 11,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "checkBox",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 11,
            Field_Name: "Makini No.",
            Serial_no: 12,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 12,
            Field_Name: "Location Address",
            Serial_no: 13,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 13,
            Field_Name: "Latitude",
            Serial_no: 14,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 14,
            Field_Name: "Longitude",
            Serial_no: 15,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 15,
            Field_Name: "No. of Floors",
            Serial_no: 16,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 16,
            Field_Name: "Indemnity Period Unit",
            Serial_no: 17,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "DropDown",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 17,
            Field_Name: "Indemnity Period",
            Serial_no: 18,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 18,
            Field_Name: "PML%",
            Serial_no: 19,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 19,
            Field_Name: "PML Amount",
            Serial_no: 20,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 20,
            Field_Name: "Survey Required Y/N",
            Serial_no: 21,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "checkBox",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 21,
            Field_Name: "Watchman Y/N",
            Serial_no: 22,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "checkBox",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 22,
            Field_Name: "CCTV System",
            Serial_no: 22,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "checkBox",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 23,
            Field_Name: "Burglary Alarm System Y/N",
            Serial_no: 22,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "checkBox",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 24,
            Field_Name: "Warehouse Yes/No",
            Serial_no: 22,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "0",
            Updatable_yn: "1",
            Field_type: "checkBox",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
        ],
      },
    ],
  },
  contentDetails: {
    key: 76402,
    Objects: [
      {
        Id: "R_116",
        Object_name: "Content Details",
        Fields: [
          {
            Field_Id: 1,
            Field_Name: "Sr No",
            Serial_no: 1,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "0",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 2,
            Field_Name: "Name of the Conent",
            Serial_no: 2,
            Data_Type: "Date",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "0",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 3,
            Field_Name: "No of units",
            Serial_no: 3,
            Data_Type: "Date",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "0",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 4,
            Field_Name: "Serial No",
            Serial_no: 4,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "inputText",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 5,
            Field_Name: "Sum Insured",
            Serial_no: 5,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
          {
            Field_Id: 6,
            Field_Name: "Total Sum Insured",
            Serial_no: 6,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: "inputNumber",
            List_values_source: null,
            Group_name: null,
            Hide_yn: "0",
            Claimlookup_yn: "0",
          },
        ],
      },
    ],
  },
};

export const riskFactorData = {
  data: [
    {
      key: 2301,
      Objects: [
        {
          RiskId: "R_01",
          Object_name: "Vehicle Details",
          Fields: [
            {
              "Field Id": 1,
              "Field Name": "Vehicle ID",
              Value: 1,
            },
            {
              "Field Id": 2,
              "Field Name": "Vehicle Entry Date",
              Value: "01-01-2024",
            },
            {
              "Field Id": 3,
              "Field Name": "Vehicle Exit Date",
              Value: "31-12-2024",
            },
            {
              "Field Id": 4,
              "Field Name": "Coverage Type",
              Value: "01-Comprehensive",
            },
            {
              "Field Id": 5,
              "Field Name": "Usage Type",
              Value: "001-Private Car",
            },
            {
              "Field Id": 6,
              "Field Name": "Body Type ",
              Value: "10101A-SUV",
            },
            {
              "Field Id": 7,
              "Field Name": "Make",
              Value: "101-AUDI",
            },
            {
              "Field Id": 8,
              "Field Name": "Model",
              Value: "10101-AUDI 80",
            },
            {
              "Field Id": 9,
              "Field Name": "Year of Manufacturing",
              Value: 2015,
            },
            {
              "Field Id": 10,
              "Field Name": "Vehicle Age",
              Value: 9,
            },
            {
              "Field Id": 11,
              "Field Name": "Engine No.",
              Value: "E10011001",
            },
            {
              "Field Id": 12,
              "Field Name": "Chassis No.",
              Value: "CH2001001",
            },
            {
              "Field Id": 13,
              "Field Name": "Registration Number",
              Value: "RE30011001",
            },
            {
              "Field Id": 14,
              "Field Name": "CC",
              Value: 1600,
            },
            {
              "Field Id": 15,
              "Field Name": "Fuel Type",
              Value: "Petrol",
            },
            {
              "Field Id": 16,
              "Field Name": "Vehicle Value",
              Value: 2000000,
            },
            {
              "Field Id": 17,
              "Field Name": "Seating",
              Value: 5,
            },
            {
              "Field Id": 18,
              "Field Name": "GVW",
              Value: 2000,
            },
            {
              "Field Id": 19,
              "Field Name": "Number of Claims",
              Value: 0,
            },
            {
              "Field Id": 20,
              "Field Name": "Number of Claim Free Years",
              Value: 0,
            },
            {
              "Field Id": 21,
              "Field Name": "Sum Insured Currency",
              Value: "AED",
            },
            {
              "Field Id": 22,
              "Field Name": "Premium Currency",
              Value: "AED",
            },
          ],
        },
      ],
    },
  ],
};
