export const getQuotesInitialData = [
  {
    quotation: "",
    product: "",
    start_date: "",
    end_date: "",
    status: "",
  },
];

export const getquotesOption = [
  {
    type: "motor",
    name: "1001-Motor Comprehension",
    code: 10,
  },
  {
    type: "motor",
    name: "1002-Motor Private",
    code: 20,
  },
  {
    type: "marine",
    name: "1003-Marine Open Cover",
    code: 30,
  },
  {
    type: "fire",
    name: "1004-Fire Open Cover",
    code: 40,
  },
];

export const getQuotesTableData = [
  {
    id: 1,
    quotation: "Q/10/1001/2024/0543",
    product: "Motor Comprehension",
    start_date: "10/01/2024",
    end_date: "10/01/2024",
    status: "Pending",
  },
  {
    id: 2,
    quotation: "Q/10/1001/2024/0544",
    product: "Motor Private",
    start_date: "10/01/2024",
    end_date: "10/01/2024",
    status: "Pending",
  },
];

export const headerFormOptionData = {
  product: [
    { name: "1-Product", code: 1 },
    { name: "2-Product", code: 2 },
  ],
  branch: [
    { Code: "03", name: "Mbeya Branch" },
    { Code: "01", name: "Head Office" },
    { Code: "02", name: "Mwanza Branch" },
    { Code: "04", name: "Arusha Branch" },
    { Code: "06", name: "Mbagala Branch" },
    { Code: "05", name: "Dodoma Branch" },
    { Code: "07", name: "Digital-sure Branch" },
    { Code: "08", name: "Zanzibar Branch" },
  ],
  businessType: [
    { code: "01", name: "Direct without coisurance" },
    { code: "02", name: "Direct with Coinsurance" },
  ],
  sourceType: [
    { code: "01", name: "Direct" },
    { code: "02", name: "Agent" },
    { code: "03", name: "Broker" },
  ],
  unit: [{code:'1', name:"Hour"}, {code:'2', name:"Day"}, {code:'3', name:"Week"}, {code:'4', name:"Month"}, {code:'5', name:"Year"}],
  premiumType: ["Pro-Rate", "Short Period", "Normal/Annual", "Fixed Rate"],
  paymentMode: ["Bank Guarantee", "Credit Customer", "Others"],
  installment: ["Annual", "Half-Yearly", "Quarterly", "Monthly"],
  state: ["Tamil Nadu", "Karnataka", "Andra"],
  city: ["chennai", "Coimbatore"],
  area: ["Tiruvanmiyur", "Adayar", "Perungudi"],
};

export const searchDisplayData = {
  data: [
    { id: 'DC0001001', name: "Shankar", email: "shankar@gmail.com", phoneno: 9876543210 },
    { id: 'BL1011470', name: "Hari", email: "sari@gmail.com", phoneno: 1234567890 },
    { id: 'sa1011580', name: "Siva", email: "hiva@gmail.com", phoneno: 9090909090 },
  ],
};

export const searchDisplayHeader = [
  { field: "name", header: "Name" },
  { field: "email", header: "Email" },
  { field: "phoneno", header: "Phoneno" },
];

export const getQuotesHeaderFromRender = {
  partyDetails: [
    {
      name: "partyRole",
      label: "Party Role",
      fieldType: "dropDown",
      required: true,
    },
    {
      name: "partyID",
      label: "Party ID",
      fieldType: "overlay",
      required: true,
    },
    {
      name: "address",
      label: "Address",
      fieldType: "partyAddress",
    },
  ],
  formData: [
    { name: "plan", label: "plan", fieldType: "autoComplete", required: true },
    { name: "branch", label: "Branch", fieldType: "dropDown", required: true },
    {
      name: "department",
      label: "department",
      fieldType: "inputText",
      required: true,
    },
    {
      name: "businessType",
      label: "business type",
      fieldType: "dropDown",
      required: true,
    },
    {
      name: "quotaion",
      label: "quotaion#",
      fieldType: "inputText",
      disabled: true,
      readonly: true,
    },
    { name: "recordDate", label: "quote record Date", fieldType: "dateType" },
    // {
    //   name: "customer",
    //   label: "customer",
    //   fieldType: "overlay",
    //   required: true,
    // },
    // { name: "insured", label: "insured", fieldType: "overlay", required: true },
    // { name: "sourceCode", label: "source Code", fieldType: "autoComplete" },
    { name: "sourceType", label: "source type", fieldType: "dropDown" },
    { name: "unit", label: "unit", fieldType: "dropDown" },
    { name: "period", label: "period", fieldType: "inputNumber" },
    { name: "issueDate", label: "issue date", fieldType: "dateType" },
    {
      name: "periodFrom",
      label: "period form",
      fieldType: "dateType",
      required: true,
    },
    {
      name: "periodTo",
      label: "period to",
      fieldType: "dateType",
      required: true,
    },
    {
      name: "premiumType",
      label: "premium calculate type",
      fieldType: "dropDown",
      required: true,
    },
    { name: "currency", label: "SI currency", fieldType: "autoComplete" },
    {
      name: "premiumCurrency",
      label: "premium currency",
      fieldType: "autoComplete",
    },
    { name: "paymentMode", label: "mode of payment", fieldType: "inputText" },
    { name: "installment", label: "installment Method", fieldType: "dropDown" },
    {
      name: "hypothecation",
      label: "hypothecation Yes / No",
      fieldType: "checkBox",
    },
    {
      name: "preInspection",
      label: "pre-inspection yes / no",
      fieldType: "checkBox",
    },
    { name: "territory", label: "territory", fieldType: "inputText" },
    { name: "oldPolicy", label: "old Policy #", fieldType: "inputText" },
    { name: "fleet", label: "fleet yes / no", fieldType: "checkBox" },
    {
      name: "gracePeriod",
      label: "grace period yes / no",
      fieldType: "checkBox",
    },
    {
      name: "gracePeriodEnd",
      label: "grace period end date",
      fieldType: "dateType",
    },
    { name: "cbc", label: "CBC yes / No", fieldType: "checkBox" },
    {
      name: "coverNoteId",
      label: "cover note book id",
      fieldType: "autoComplete",
    },
    { name: "coverNote", label: "cover note", fieldType: "inputText" },
    { name: "coverNoteDate", label: "cover note date", fieldType: "dateType" },
    { name: "state", label: "State", fieldType: "dropDown" },
    { name: "city", label: "City", fieldType: "dropDown" },
    { name: "area", label: "Area", fieldType: "dropDown" },
    {
      name: "address",
      label: "Address",
      fieldType: "address",
    },
  ],
};

export const getQuotesHeaderData = {
  partyDetails: [
    {partyRole: "Customer", partyID: "", address: "" },
    {partyRole: "Insured", partyID: "", address: "" },
  ],
  formData: {
    branch: "01-Head Office" ,
    department: "11-Motor UW department",
    businessType: "1-Direct with Coinsurance",
    quotaion: "",
    recordDate: "07/06/2024 08:31",
    // customer: "",
    // insured: "",
    // sourceCode: "",
    sourceType: "",
    unit: "Day",
    period: "365",
    issueDate: "",
    periodFrom: "",
    periodTo: "",
    premiumType: "Normal/Annual",
    currency: "",
    premiumCurrency: "",
    paymentMode: "Credit Customer",
    installment: "Quarterly",
    hypothecation: "",
    preInspection: "",
    territory: "",
    oldPolicy: "",
    fleet: "",
    gracePeriod: "",
    gracePeriodEnd: "",
    cbc: "",
    coverNoteId: "",
    coverNote: "",
    coverNoteDate: "",
    address: "",
    plan: "",
  },
};

export const getQuotesTabData = {
  discountLoading: {
    value: [
      { name: "Own Damage", code: "3101", mandatory: true },
      { name: "Third party Death ", code: "3176", mandatory: true },
      { name: "Third party property damage", code: "3178", mandatory: true },
      { name: "PA Benefit to Driver", code: "3106", mandatory: false },
      { name: "Road Assistance", code: "3195", mandatory: false },
      { name: "Agency Repair", code: "3103", mandatory: false },
      { name: "Natural Calamity Cover", code: "3104", mandatory: false },
      { name: "Geographical Extension", code: "3105", mandatory: false },
      { name: "Personal Accident Passenger", code: "3102", mandatory: false },
    ],
  },
};

export const getQuotesTableHeaderData = {
  discountLoading: {
    header: [
      { field: "code", header: "Code", fieldType: "dropDown" },
      {
        field: "description",
        header: "Description",
        fieldType: "inputTextarea",
      },
      { field: "rate", header: "Rate", fieldType: "inputNumber" },
      { field: "rateper", header: "Rate Per", fieldType: "inputNumber" },
      { field: "amounttc", header: "Amount TC", fieldType: "inputNumber" },
      { field: "amountlc", header: "Amount LC", fieldType: "inputNumber" },
      {
        field: "canscadeOrder",
        header: "Cascade Order",
        fieldType: "inputNumber",
      },
      { field: "applied", header: "Applied On", fieldType: "dropDown" },
      {
        field: "brokercomm",
        header: "Broker Comm. Appl",
        fieldType: "checkBox",
      },
      { field: "ncb", header: "NCB Yes / NO", fieldType: "checkBox" },
      { field: "save", header: "" },
      { field: "action", header: "" },
    ],
  },
  deductible: {
    header: [
      { field: "code", header: "Code", fieldType: "inputText" },
      {
        field: "description",
        header: "Description",
        fieldType: "inputTextarea",
      },
      {
        field: "deductibleType",
        header: "Deductible Type",
        fieldType: "inputNumber",
      },
      { field: "percentage", header: "%", fieldType: "inputNumber" },
      { field: "amounttc", header: "Amount TC", fieldType: "inputNumber" },
      { field: "amountlc", header: "Amount LC", fieldType: "inputNumber" },
      { field: "save", header: "" },
      { field: "action", header: "" },
    ],
  },
  conditions: {
    header: [
      { field: "code", header: "Code", fieldType: "dropDown" },
      {
        field: "description",
        header: "Description",
        fieldType: "inputTextarea",
      },
      {
        field: "longDescription",
        header: "Long Description",
        fieldType: "inputTextarea",
      },
      {
        field: "longDescription2",
        header: "Long Description",
        fieldType: "inputTextarea",
      },
      {
        field: "conditionType",
        header: "Condition Type",
        fieldType: "inputNumber",
      },
      { field: "save", header: "" },
      { field: "action", header: "" },
    ],
  },
  chargeTax: {
    header: [
      { field: "type", header: "Type", fieldType: "autoComplete" },
      { field: "charge", header: "Charge", fieldType: "autoComplete" },
      { field: "level", header: "Level", fieldType: "inputNumber" },
      { field: "rate", header: "Rate", fieldType: "inputNumber" },
      { field: "rateper", header: "Rate Per", fieldType: "inputNumber" },
      {
        field: "customerPercentage",
        header: "Customer %",
        fieldType: "inputNumber",
      },
      { field: "chargetc", header: "Charge TC", fieldType: "inputNumber" },
      { field: "chargelc", header: "Charge LC", fieldType: "inputNumber" },
      { field: "save", header: "" },
      { field: "action", header: "" },
    ],
  },
  commission: {
    header: [
      { field: "agent", header: "Agent", fieldType: "dropDown" },
      { field: "commission", header: "Commission", fieldType: "dropDown" },
      { field: "appliedOn", header: "Applied On", fieldType: "dropDown" },
      { field: "currency", header: "Currency", fieldType: "inputNumber" },
      {
        field: "commissiontc",
        header: "Commission TC",
        fieldType: "inputNumber",
      },
      {
        field: "commissionlc",
        header: "Commission LC",
        fieldType: "inputNumber",
      },
      { field: "save", header: "" },
      { field: "action", header: "" },
    ],
  },
  applicableCurrency: {
    header: [
      { field: "currency", header: "Currency", fieldType: "autoComplete" },
      { field: "rateType", header: "Rate Type", fieldType: "dropDown" },
      { field: "dollar", header: "US Dollar", fieldType: "inputNumber" },
      { field: "rupee", header: "Indian Rupees", fieldType: "inputText" },
      { field: "yen", header: "japaneseYen", fieldType: "inputText" },
      { field: "save", header: "" },
      { field: "action", header: "" },
    ],
  },
  hypothecation: {
    header: [
      { field: "sri", header: "Serial No.", fieldType: "inputText" },
      { field: "financier", header: "Financier", fieldType: "dropDown" },
      { field: "hypoType", header: "Hypo. Type", fieldType: "dropDown" },
      { field: "ref", header: "Reference", fieldType: "inputText" },
      { field: "webite", header: "Webite", fieldType: "inputText" },
      { field: "phone", header: "Phone", fieldType: "inputNumber" },
      { field: "save", header: "" },
      { field: "action", header: "" },
    ],
  },
  prevInsurenceDetails: {
    header: [
      { field: "insurer", header: "Insurer", fieldType: "inputText" },
      { field: "fromDate", header: "From Date", fieldType: "dateField" },
      { field: "uwYear", header: "UW Year", fieldType: "inputText" },
      { field: "plicy", header: "Policy", fieldType: "inputText" },
      { field: "sumInsured", header: "Sum Insured", fieldType: "inputText" },
      { field: "premium", header: "Premium", fieldType: "inputText" },
      { field: "claim", header: "Claim", fieldType: "inputText" },
      { field: "claimRatio", header: "Claim Ratio", fieldType: "inputNumber" },
      { field: "save", header: "" },
      { field: "action", header: "" },
    ],
  },
  surveyorDetails: {
    header: [
      { field: "surveyor", header: "Surveyor", fieldType: "dropDown" },
      { field: "feesType", header: "Fees Type", fieldType: "dropDown" },
      {
        field: "calculationType",
        header: "Calculation Type",
        fieldType: "dropDown",
      },
      { field: "currency", header: "Currency", fieldType: "dropDown" },
      { field: "feesTc", header: "Fees TC", fieldType: "inputText" },
      { field: "feesLc", header: "Fees LC", fieldType: "inputText" },
      { field: "save", header: "" },
      { field: "action", header: "" },
    ],
  },
  riDetails: {
    header: [
      { field: "riBasic", header: "RI Basic", fieldType: "dropDown" },
      { field: "cedingBasis", header: "Ceding Basis", fieldType: "dropDown" },
      { field: "riPremType", header: "RI Prem Type", fieldType: "dropDown" },
      {
        field: "deductRi",
        header: "Deduct RI Communication",
        fieldType: "dropDown",
      },
      {
        field: "endAllocation",
        header: "End Allocation",
        fieldType: "dropDown",
      },
      { field: "facProvOn", header: "FAC Prov. On", fieldType: "dropDown" },
      { field: "save", header: "", fieldType: "" },
    ],
  },
};

export const quotesTabTableInitialData = {
  discountLoading: {
    value: [
      {
        code: "",
        description: "",
        rate: "",
        ratePer: "",
        amountTC: "",
        amountLC: "",
        order: "",
        commAppl: "",
        nub: "",
      },
    ],
  },
  deductible: {
    value: [
      {
        code: "",
        description: "",
        deductibleType: "",
        percentage: "",
        amounttc: "",
        amountlc: "",
      },
    ],
  },
  conditions: {
    value: [
      {
        code: "",
        description: "",
        longDescription: "",
        longDescription2: "",
        conditionType: "",
      },
    ],
  },
  chargeTax: {
    value: [
      {
        type: "",
        charge: "",
        level: "",
        rate: "",
        rateper: "",
        customerPercentage: "",
        chargetc: "",
        chargelc: "",
      },
    ],
  },
  commission: {
    value: [
      {
        agent: "",
        commission: "",
        appliedOn: "",
        currency: "",
        commissiontc: "",
        commissionlc: "",
      },
    ],
  },
  applicableCurrency: {
    value: [
      {
        currency: "",
        rateType: "",
        dollar: "",
        rupee: "",
        yen: "",
        save: "",
      },
    ],
  },
  hypothecation: {
    value: [
      {
        sri: "",
        financier: "",
        hypoType: "",
        ref: "",
        webite: "",
        phone: "",
        save: "",
      },
    ],
  },
  prevInsurenceDetails: {
    value: [
      {
        insurer: "",
        fromDate: "",
        uwYear: "",
        plicy: "",
        sumInsured: "",
        premium: "",
        claim: "",
        claimRatio: "",
        save: "",
      },
    ],
  },
  surveyorDetails: {
    value: [
      {
        surveyor: "",
        feesType: "",
        calculationType: "",
        currency: "",
        feesTc: "",
        feesLc: "",
        save: "",
      },
    ],
  },
  riDetails: {
    value: [
      {
        riBasic: "",
        cedingBasis: "",
        riPremType: "",
        deductRi: "",
        endAllocation: "",
        facProvOn: "",
      },
    ],
  },
};

export const riskBlock = [
  {
    Id: "R_01",
    name: "vehicleDetails",
    Object_name: "Vehicle Details",
    Parent_Object_Id: null,
    Level: 1,
    Serial_no: 1,
    Object_Type: "2",
    Submenu: [
      {
        Id: "R_16",
        name: "geographicDetail",
        Object_name: "Geographical Extension",
        Parent_Object_Id: "R_01",
        Level: 2,
        Serial_no: 1,
        Object_Type: "2",
      },
    ],
  },
  {
    Id: "R_02",
    name: "driverDetails",
    Object_name: "Driver Details",
    Parent_Object_Id: null,
    Level: 1,
    Serial_no: 2,
    Object_Type: "2",
    submenu: [],
  },
];

export const riskAssesmentFactor = {
  vehicleDetails: {
    key: 2301,
    Objects: [
      {
        Id: "R_01",
        Object_name: "Vehicle Details",
        Fields: [
          {
            Field_Id: 1132104327,
            Field_Name: "Type of Cover",
            Serial_no: 10,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132104498,
            Field_Name: "Vehicle ID*",
            Serial_no: 1,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "0",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132104951,
            Field_Name: "Sticker No",
            Serial_no: 4,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132104516,
            Field_Name: "Usage Type",
            Serial_no: 9,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132104517,
            Field_Name: "Make*",
            Serial_no: 11,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132104521,
            Field_Name: "Model",
            Serial_no: 12,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132104515,
            Field_Name: "Vehicle Category",
            Serial_no: 13,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132105224,
            Field_Name: "Body Type",
            Serial_no: 14,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132104330,
            Field_Name: "Reg. No.",
            Serial_no: 17,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132104328,
            Field_Name: "Chassis No.",
            Serial_no: 18,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132104329,
            Field_Name: "Engine No.",
            Serial_no: 19,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132104340,
            Field_Name: "Mfg Year",
            Serial_no: 21,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132104523,
            Field_Name: "Colour",
            Serial_no: 24,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132111892,
            Field_Name: "Fuel Type",
            Serial_no: 26,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132104499,
            Field_Name: "Vehicle Value",
            Serial_no: 31,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132108037,
            Field_Name: "CC",
            Serial_no: 33,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132111897,
            Field_Name: "Product",
            Serial_no: null,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
        ],
      },
    ],
  },
  driverDetails: {
    key: 2301,
    Objects: [
      {
        Id: "R_02",
        Object_name: "Driver Details",
        Fields: [
          {
            Field_Id: 1132104600,
            Field_Name: "Licence No.*",
            Serial_no: 2,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132104610,
            Field_Name: "Nationality*",
            Serial_no: 5,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132104687,
            Field_Name: "Date of Birth",
            Serial_no: 6,
            Data_Type: "Date",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132104690,
            Field_Name: "Age*",
            Serial_no: 7,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "0",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132104611,
            Field_Name: "Sex*",
            Serial_no: 8,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
        ],
      },
    ],
  },
  geographicDetail: {
    key: 2301,
    Objects: [
      {
        Id: "R_16",
        Object_name: "Geographical Extension",
        Fields: [
          {
            Field_Id: 1132111289,
            Field_Name: "Country",
            Serial_no: 2,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132104849,
            Field_Name: "Extension\nPeriod Units",
            Serial_no: 4,
            Data_Type: "Text",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132104853,
            Field_Name: "Extension Period",
            Serial_no: 6,
            Data_Type: "Number",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132104851,
            Field_Name: "Valid From",
            Serial_no: 7,
            Data_Type: "Date",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "1",
            Field_type: null,
            List_values_source: null,
          },
          {
            Field_Id: 1132104852,
            Field_Name: "Valid To",
            Serial_no: 8,
            Data_Type: "Date",
            Default_Value: null,
            Mandatory_yn: "1",
            Updatable_yn: "0",
            Field_type: null,
            List_values_source: null,
          },
        ],
      },
    ],
  },
};
